In [1]:
import re
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

%matplotlib inline 

import warnings 
warnings.filterwarnings("ignore")

#### Gather & Asses 

In [2]:
df2020 = pd.read_csv('survey_results2020.csv')
df2020.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
  

In [3]:
df2020.MainBranch.unique()

array(['I am a developer by profession', 'I code primarily as a hobby',
       'I used to be a developer by profession, but no longer am',
       'I am not primarily a developer, but I write code sometimes as part of my work',
       'I am a student who is learning to code', nan], dtype=object)

In [4]:
df2020.Employment.unique()

array(['Independent contractor, freelancer, or self-employed',
       'Employed full-time', nan, 'Student',
       'Not employed, but looking for work', 'Employed part-time',
       'Retired', 'Not employed, and not looking for work'], dtype=object)

In [5]:
df2020.JobSat.unique()

array(['Slightly satisfied', 'Very dissatisfied', nan,
       'Slightly dissatisfied', 'Very satisfied',
       'Neither satisfied nor dissatisfied'], dtype=object)

***

In [40]:
df2019 = pd.read_csv('survey_results2019.csv')
len(df2019.columns)

85

In [11]:
df2019.MainBranch.unique()

array(['I am a student who is learning to code',
       'I am not primarily a developer, but I write code sometimes as part of my work',
       'I am a developer by profession', 'I code primarily as a hobby',
       'I used to be a developer by profession, but no longer am', nan],
      dtype=object)

In [12]:
df2019.Employment.unique()

array(['Not employed, and not looking for work',
       'Not employed, but looking for work', 'Employed full-time',
       'Independent contractor, freelancer, or self-employed', nan,
       'Employed part-time', 'Retired'], dtype=object)

In [13]:
df2019.JobSat.unique()

array([nan, 'Slightly satisfied', 'Slightly dissatisfied',
       'Neither satisfied nor dissatisfied', 'Very satisfied',
       'Very dissatisfied'], dtype=object)

***

In [14]:
df2018 = pd.read_csv('survey_results2018.csv')
df2018.columns

Index(['Respondent', 'Hobby', 'OpenSource', 'Country', 'Student', 'Employment',
       'FormalEducation', 'UndergradMajor', 'CompanySize', 'DevType',
       ...
       'Exercise', 'Gender', 'SexualOrientation', 'EducationParents',
       'RaceEthnicity', 'Age', 'Dependents', 'MilitaryUS', 'SurveyTooLong',
       'SurveyEasy'],
      dtype='object', length=129)

In [18]:
df2018.columns[:50]

Index(['Respondent', 'Hobby', 'OpenSource', 'Country', 'Student', 'Employment',
       'FormalEducation', 'UndergradMajor', 'CompanySize', 'DevType',
       'YearsCoding', 'YearsCodingProf', 'JobSatisfaction',
       'CareerSatisfaction', 'HopeFiveYears', 'JobSearchStatus', 'LastNewJob',
       'AssessJob1', 'AssessJob2', 'AssessJob3', 'AssessJob4', 'AssessJob5',
       'AssessJob6', 'AssessJob7', 'AssessJob8', 'AssessJob9', 'AssessJob10',
       'AssessBenefits1', 'AssessBenefits2', 'AssessBenefits3',
       'AssessBenefits4', 'AssessBenefits5', 'AssessBenefits6',
       'AssessBenefits7', 'AssessBenefits8', 'AssessBenefits9',
       'AssessBenefits10', 'AssessBenefits11', 'JobContactPriorities1',
       'JobContactPriorities2', 'JobContactPriorities3',
       'JobContactPriorities4', 'JobContactPriorities5', 'JobEmailPriorities1',
       'JobEmailPriorities2', 'JobEmailPriorities3', 'JobEmailPriorities4',
       'JobEmailPriorities5', 'JobEmailPriorities6', 'JobEmailPriorities7'],
  

In [19]:
df2018.columns[50:]

Index(['UpdateCV', 'Currency', 'Salary', 'SalaryType', 'ConvertedSalary',
       'CurrencySymbol', 'CommunicationTools', 'TimeFullyProductive',
       'EducationTypes', 'SelfTaughtTypes', 'TimeAfterBootcamp',
       'HackathonReasons', 'AgreeDisagree1', 'AgreeDisagree2',
       'AgreeDisagree3', 'LanguageWorkedWith', 'LanguageDesireNextYear',
       'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'FrameworkWorkedWith',
       'FrameworkDesireNextYear', 'IDE', 'OperatingSystem', 'NumberMonitors',
       'Methodology', 'VersionControl', 'CheckInCode', 'AdBlocker',
       'AdBlockerDisable', 'AdBlockerReasons', 'AdsAgreeDisagree1',
       'AdsAgreeDisagree2', 'AdsAgreeDisagree3', 'AdsActions',
       'AdsPriorities1', 'AdsPriorities2', 'AdsPriorities3', 'AdsPriorities4',
       'AdsPriorities5', 'AdsPriorities6', 'AdsPriorities7', 'AIDangerous',
       'AIInteresting', 'AIResponsible', 'AIFuture', 'EthicsChoice',
       'EthicsReport'

In [16]:
df2018.Employment.unique()

array(['Employed part-time', 'Employed full-time',
       'Independent contractor, freelancer, or self-employed',
       'Not employed, and not looking for work',
       'Not employed, but looking for work', nan, 'Retired'], dtype=object)

In [17]:
df2018.JobSatisfaction.unique()

array(['Extremely satisfied', 'Moderately dissatisfied',
       'Moderately satisfied', 'Neither satisfied nor dissatisfied',
       'Slightly satisfied', nan, 'Slightly dissatisfied',
       'Extremely dissatisfied'], dtype=object)

***

In [20]:
df2017 = pd.read_csv('survey_results2017.csv')
df2017.columns

Index(['Respondent', 'Professional', 'ProgramHobby', 'Country', 'University',
       'EmploymentStatus', 'FormalEducation', 'MajorUndergrad', 'HomeRemote',
       'CompanySize',
       ...
       'StackOverflowMakeMoney', 'Gender', 'HighestEducationParents', 'Race',
       'SurveyLong', 'QuestionsInteresting', 'QuestionsConfusing',
       'InterestedAnswers', 'Salary', 'ExpectedSalary'],
      dtype='object', length=154)

In [21]:
df2017.columns[:50]

Index(['Respondent', 'Professional', 'ProgramHobby', 'Country', 'University',
       'EmploymentStatus', 'FormalEducation', 'MajorUndergrad', 'HomeRemote',
       'CompanySize', 'CompanyType', 'YearsProgram', 'YearsCodedJob',
       'YearsCodedJobPast', 'DeveloperType', 'WebDeveloperType',
       'MobileDeveloperType', 'NonDeveloperType', 'CareerSatisfaction',
       'JobSatisfaction', 'ExCoderReturn', 'ExCoderNotForMe', 'ExCoderBalance',
       'ExCoder10Years', 'ExCoderBelonged', 'ExCoderSkills',
       'ExCoderWillNotCode', 'ExCoderActive', 'PronounceGIF', 'ProblemSolving',
       'BuildingThings', 'LearningNewTech', 'BoringDetails', 'JobSecurity',
       'DiversityImportant', 'AnnoyingUI', 'FriendsDevelopers',
       'RightWrongWay', 'UnderstandComputers', 'SeriousWork',
       'InvestTimeTools', 'WorkPayCare', 'KinshipDevelopers',
       'ChallengeMyself', 'CompetePeers', 'ChangeWorld', 'JobSeekingStatus',
       'HoursPerWeek', 'LastNewJob', 'AssessJobIndustry'],
      dtype='obj

In [22]:
df2017.columns[50:100]

Index(['AssessJobRole', 'AssessJobExp', 'AssessJobDept', 'AssessJobTech',
       'AssessJobProjects', 'AssessJobCompensation', 'AssessJobOffice',
       'AssessJobCommute', 'AssessJobRemote', 'AssessJobLeaders',
       'AssessJobProfDevel', 'AssessJobDiversity', 'AssessJobProduct',
       'AssessJobFinances', 'ImportantBenefits', 'ClickyKeys', 'JobProfile',
       'ResumePrompted', 'LearnedHiring', 'ImportantHiringAlgorithms',
       'ImportantHiringTechExp', 'ImportantHiringCommunication',
       'ImportantHiringOpenSource', 'ImportantHiringPMExp',
       'ImportantHiringCompanies', 'ImportantHiringTitles',
       'ImportantHiringEducation', 'ImportantHiringRep',
       'ImportantHiringGettingThingsDone', 'Currency', 'Overpaid',
       'TabsSpaces', 'EducationImportant', 'EducationTypes', 'SelfTaughtTypes',
       'TimeAfterBootcamp', 'CousinEducation', 'WorkStart',
       'HaveWorkedLanguage', 'WantWorkLanguage', 'HaveWorkedFramework',
       'WantWorkFramework', 'HaveWorkedDatabase'

In [23]:
df2017.columns[100:]

Index(['CheckInCode', 'ShipIt', 'OtherPeoplesCode', 'ProjectManagement',
       'EnjoyDebugging', 'InTheZone', 'DifficultCommunication',
       'CollaborateRemote', 'MetricAssess', 'EquipmentSatisfiedMonitors',
       'EquipmentSatisfiedCPU', 'EquipmentSatisfiedRAM',
       'EquipmentSatisfiedStorage', 'EquipmentSatisfiedRW',
       'InfluenceInternet', 'InfluenceWorkstation', 'InfluenceHardware',
       'InfluenceServers', 'InfluenceTechStack', 'InfluenceDeptTech',
       'InfluenceVizTools', 'InfluenceDatabase', 'InfluenceCloud',
       'InfluenceConsultants', 'InfluenceRecruitment',
       'InfluenceCommunication', 'StackOverflowDescribes',
       'StackOverflowSatisfaction', 'StackOverflowDevices',
       'StackOverflowFoundAnswer', 'StackOverflowCopiedCode',
       'StackOverflowJobListing', 'StackOverflowCompanyPage',
       'StackOverflowJobSearch', 'StackOverflowNewQuestion',
       'StackOverflowAnswer', 'StackOverflowMetaChat',
       'StackOverflowAdsRelevant', 'StackOverflo

In [26]:
df2017.EmploymentStatus.unique()

array(['Not employed, and not looking for work', 'Employed part-time',
       'Employed full-time',
       'Independent contractor, freelancer, or self-employed',
       'Not employed, but looking for work', 'I prefer not to say',
       'Retired'], dtype=object)

In [24]:
df2017.JobSatisfaction.unique()

array([nan,  9.,  3.,  8.,  6.,  7.,  5.,  4., 10.,  2.,  0.,  1.])

***

In [27]:
df2016 = pd.read_csv('survey_results2016.csv')
df2016.columns

Index(['Unnamed: 0', 'collector', 'country', 'un_subregion', 'so_region',
       'age_range', 'age_midpoint', 'gender', 'self_identification',
       'occupation', 'occupation_group', 'experience_range',
       'experience_midpoint', 'salary_range', 'salary_midpoint',
       'big_mac_index', 'tech_do', 'tech_want', 'aliens',
       'programming_ability', 'employment_status', 'industry',
       'company_size_range', 'team_size_range', 'women_on_team', 'remote',
       'job_satisfaction', 'job_discovery', 'dev_environment',
       'commit_frequency', 'hobby', 'dogs_vs_cats', 'desktop_os',
       'unit_testing', 'rep_range', 'visit_frequency', 'why_learn_new_tech',
       'education', 'open_to_new_job', 'new_job_value', 'job_search_annoyance',
       'interview_likelihood', 'how_to_improve_interview_process',
       'star_wars_vs_star_trek', 'agree_tech', 'agree_notice',
       'agree_problemsolving', 'agree_diversity', 'agree_adblocker',
       'agree_alcohol', 'agree_loveboss', 'agree_n

In [30]:
df2016.employment_status.unique()

array([nan, 'Employed full-time', 'Freelance / Contractor',
       'Self-employed', "I'm a student", 'Unemployed',
       'Prefer not to disclose', 'Employed part-time',
       'Other (please specify)', 'Retired'], dtype=object)

In [28]:
df2016.job_satisfaction.unique()

array([nan, 'I love my job', "I don't have a job",
       "I'm somewhat satisfied with my job",
       "I'm somewhat dissatisfied with my job",
       "I'm neither satisfied nor dissatisfied", 'Other (please specify)',
       'I hate my job'], dtype=object)

***

In [32]:
df2015 = pd.read_csv('survey_results2015.csv', header=1)
df2015.columns

Index(['Country', 'Age', 'Gender', 'Tabs or Spaces',
       'Years IT / Programming Experience', 'Occupation',
       'Desktop Operating System', 'Desktop Operating System: write-in',
       'Current Lang & Tech: Android', 'Current Lang & Tech: Arduino',
       ...
       'Why use Stack Overflow: I don't use Stack Overflow',
       'How often are Stack Overflow's answers helpful',
       'Why answer: Help a programmer in need',
       'Why answer: Help future programmers',
       'Why answer: Demonstrate expertise', 'Why answer: Self promotion',
       'Why answer: Sense of responsibility to developers',
       'Why answer: No idea', 'Why answer: I don't answer and I don't want to',
       'Why answer: I don't answer but I want to'],
      dtype='object', length=222)

In [33]:
df2015.columns[:50]

Index(['Country', 'Age', 'Gender', 'Tabs or Spaces',
       'Years IT / Programming Experience', 'Occupation',
       'Desktop Operating System', 'Desktop Operating System: write-in',
       'Current Lang & Tech: Android', 'Current Lang & Tech: Arduino',
       'Current Lang & Tech: AngularJS', 'Current Lang & Tech: C',
       'Current Lang & Tech: C++', 'Current Lang & Tech: C++11',
       'Current Lang & Tech: C#', 'Current Lang & Tech: Cassandra',
       'Current Lang & Tech: CoffeeScript', 'Current Lang & Tech: Cordova',
       'Current Lang & Tech: Clojure', 'Current Lang & Tech: Cloud',
       'Current Lang & Tech: Dart', 'Current Lang & Tech: F#',
       'Current Lang & Tech: Go', 'Current Lang & Tech: Hadoop',
       'Current Lang & Tech: Haskell', 'Current Lang & Tech: iOS',
       'Current Lang & Tech: Java', 'Current Lang & Tech: JavaScript',
       'Current Lang & Tech: LAMP', 'Current Lang & Tech: Matlab',
       'Current Lang & Tech: MongoDB', 'Current Lang & Tech: Node.j

In [34]:
df2015.columns[50:100]

Index(['Current Lang & Tech: Write-In', 'Future Lang & Tech: Android',
       'Future Lang & Tech: Arduino', 'Future Lang & Tech: AngularJS',
       'Future Lang & Tech: C', 'Future Lang & Tech: C++',
       'Future Lang & Tech: C++11', 'Future Lang & Tech: C#',
       'Future Lang & Tech: Cassandra', 'Future Lang & Tech: CoffeeScript',
       'Future Lang & Tech: Cordova', 'Future Lang & Tech: Clojure',
       'Future Lang & Tech: Cloud', 'Future Lang & Tech: Dart',
       'Future Lang & Tech: F#', 'Future Lang & Tech: Go',
       'Future Lang & Tech: Hadoop', 'Future Lang & Tech: Haskell',
       'Future Lang & Tech: iOS', 'Future Lang & Tech: Java',
       'Future Lang & Tech: JavaScript', 'Future Lang & Tech: LAMP',
       'Future Lang & Tech: Matlab', 'Future Lang & Tech: MongoDB',
       'Future Lang & Tech: Node.js', 'Future Lang & Tech: Objective-C',
       'Future Lang & Tech: Perl', 'Future Lang & Tech: PHP',
       'Future Lang & Tech: Python', 'Future Lang & Tech: R',
     

In [35]:
df2015.columns[100:150]

Index(['Training & Education: Some college, but no CS degree',
       'Training & Education: BS in CS', 'Training & Education: Masters in CS',
       'Training & Education: PhD in CS', 'Training & Education: Other',
       'Compensation', 'Compensation: midpoint', 'Employment Status',
       'Industry', 'Job Satisfaction', 'Purchasing Power', 'Remote Status',
       'Changed Jobs in last 12 Months', 'Open to new job opportunities',
       'Most important aspect of new job opportunity: Salary',
       'Most important aspect of new job opportunity: Equity',
       'Most important aspect of new job opportunity: Important decisions',
       'Most important aspect of new job opportunity: Health insurance',
       'Most important aspect of new job opportunity: Industry',
       'Most important aspect of new job opportunity: Tech stack',
       'Most important aspect of new job opportunity: Company size',
       'Most important aspect of new job opportunity: Company stage',
       'Most impor

In [36]:
df2015.columns[150:200]

Index(['Appealing message traits: Code or projects mentioned',
       'Appealing message traits: Stack Overflow activity mentioned',
       'Appealing message traits: Team described',
       'Appealing message traits: Company culture described',
       'Appealing message traits: Salary information',
       'Appealing message traits: Benefits & Perks',
       'Appealing message traits: Stack Overflow Company Page',
       'Most urgent info about job opportunity: Salary',
       'Most urgent info about job opportunity: Benefits',
       'Most urgent info about job opportunity: Company name',
       'Most urgent info about job opportunity: Tech stack',
       'Most urgent info about job opportunity: Office location',
       'Most urgent info about job opportunity: Job title',
       'Most urgent info about job opportunity: Colleagues',
       'Most urgent info about job opportunity: Product details',
       'Who do you want to communicate with about a new job opportunity: Headhunter',
   

In [37]:
df2015.columns[200:]

Index(['Source control used: I don't use source control',
       'Source control used: write-in', 'Prefered Source Control',
       'Prefered Source Control: write-in',
       'Why use Stack Overflow: Help for job',
       'Why use Stack Overflow: To give help',
       'Why use Stack Overflow: Can't do job without it',
       'Why use Stack Overflow: Maintain online presence',
       'Why use Stack Overflow: Demonstrate expertise',
       'Why use Stack Overflow: Communicate with others',
       'Why use Stack Overflow: Receive help on personal projects',
       'Why use Stack Overflow: Love to learn',
       'Why use Stack Overflow: I don't use Stack Overflow',
       'How often are Stack Overflow's answers helpful',
       'Why answer: Help a programmer in need',
       'Why answer: Help future programmers',
       'Why answer: Demonstrate expertise', 'Why answer: Self promotion',
       'Why answer: Sense of responsibility to developers',
       'Why answer: No idea', 'Why answer: I

In [38]:
df2015['Employment Status'].unique()

array(['Employed full-time', 'Freelance / Contractor',
       'Employed part-time', 'Other', nan, "I'm a student", 'Unemployed',
       'Prefer not to disclose', 'Retired'], dtype=object)

In [39]:
df2015['Job Satisfaction'].unique()

array(["I'm somewhat satisfied with my job",
       "I'm neither satisfied nor dissatisfied with my job",
       'I love my job', "I'm somewhat dissatisfied with my job",
       'I hate my job', 'Other (please specify)', nan], dtype=object)